### ISSUE TITLE
[Bug] createNodesFor is not a function since @nxrocks/nx-spring-boot 9.3.0

### ISSUE THREAD

**Issue by batnyu** [tinesoft/nxrocks#214]
### Plugin Name

@nxrocks/nx-spring-boot

### Nx Report

 NX   (0 , common_jvm_1.createNodesFor) is not a function

### Expected Behaviour

Project Graph generation to v2 API should work

### Actual Behaviour

We receive the following error :
 NX   (0 , common_jvm_1.createNodesFor) is not a function

### Steps to reproduce the behaviour

1. Install @nxrocks/nx-spring-boot 9.3.0
2. Run "nx report" or a build

**Comment by tinesoft** [comment]
Can you get me though  the actions you took **step by step**, to have the issue?
Because I cannot reproduce it...

What I did:

```
$ npx --yes create-nx-workspace@latest nx18
$ cd nx18
$ npm install --save-dev @nxrocks/nx-spring-boot@latest

$ npx nx report  (worked fined)
$ npx nx g @nxrocks/nx-spring-boot:project  (to generate a project, worked fine)
```

My Nx Report

```shell
$ npx nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : win32-x64
   npm    : 9.5.1

   nx             : 18.0.4
   @nx/js         : 18.0.4
   @nx/workspace  : 18.0.4
   @nx/devkit     : 18.0.4
   @nrwl/tao      : 18.0.4
   ---------------------------------------
   Community plugins:
   @nxrocks/nx-spring-boot : 9.3.0


```

**Comment by vixncu** [comment]
I confirm this happens to me too **after upgrading to 9.3.0**. 

For me it was like this:
1. Migrated to nx18 (from 17)
2. Upgraded @nxrocks/nx-spring-boot to 9.3.0 (using _yarn add @nxrocks/nx-spring-boot_)

And that's it. After these 2 steps, whenever I run an **nx** command I get the following error:
**(0 , common_jvm_1.createNodesFor) is not a function**

Verbose dump of the command I ran:

```
yarn run build:ui-apps --verbose

 NX   (0 , common_jvm_1.createNodesFor) is not a function


Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
If the error persists, please run "nx reset".

{
  stack: 'TypeError: (0 , common_jvm_1.createNodesFor) is not a function\n' +
    '    at createNodesFn (/Users/vixncu/IdeaProjects/virtualconfig/node_modules/@nxrocks/nx-spring-boot/src/graph/create-nodes.js:8:61)\n' +
    '    at Object.<anonymous> (/Users/vixncu/IdeaProjects/virtualconfig/node_modules/@nxrocks/nx-spring-boot/src/index.js:12:56)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n' +
    '    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n' +
    '    at Module.load (node:internal/modules/cjs/loader:1207:32)\n' +
    '    at Module._load (node:internal/modules/cjs/loader:1023:12)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1235:19)\n' +
    '    at require (node:internal/modules/helpers:176:18)\n' +
    '    at /Users/vixncu/IdeaProjects/virtualconfig/node_modules/nx/src/utils/nx-plugin.js:79:87\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async loadNxPluginAsync (/Users/vixncu/IdeaProjects/virtualconfig/node_modules/nx/src/utils/nx-plugin.js:79:38)\n' +
    '    at async loadNxPlugins (/Users/vixncu/IdeaProjects/virtualconfig/node_modules/nx/src/utils/nx-plugin.js:105:21)\n' +
    '    at async retrieveProjectConfigurations (/Users/vixncu/IdeaProjects/virtualconfig/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:45:21)\n' +
    '    at async processFilesAndCreateAndSerializeProjectGraph (/Users/vixncu/IdeaProjects/virtualconfig/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:140:28)\n' +
    '    at async getCachedSerializedProjectGraphPromise (/Users/vixncu/IdeaProjects/virtualconfig/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:43:16)\n' +
    '    at async handleRequestProjectGraph (/Users/vixncu/IdeaProjects/virtualconfig/node_modules/nx/src/daemon/server/handle-request-project-graph.js:12:24)',
  message: '(0 , common_jvm_1.createNodesFor) is not a function\n' +
    '\n' +
    'Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.\n' +
    'If the error persists, please run "nx reset".'
}
```

**Comment by dagassmann** [comment]
I use the `@nxrocks/nx-quarkus` library and ran into the same problem after upgrading from 7.2.2 to 7.3.0.
It seems the issue is that dependencies between @nxrocks libraries are managed using "*". 
After I ran the following commands which updated the libraries to the latest version it worked again:

```sh
npm i @nxrocks/common-jvm@1.2.0
npm i @nxrocks/common@3.2.0
```

Hence it works when a new workspace is created but it breaks during updates. Maybe a good approach would be to specify versions more explicitly in the respective `package.json` instead of "*".

**Comment by tinesoft** [comment]
Hi  @vixncu , @dagassmann 

Thanks for using the libraries and for the provided debug information (don't forget to ⭐ the project on Github, it helps ^^) 

@dagassmann  You might be on something indeed...

The `"*"` for the internal dependencies is required, because when publishing (which is done at once for all packages) , I don't know the exact version ahead of time. The `"*"` is to instruct `NPM` to use the **latest version** on NPM... This has always worked so far, as the `cpmmon-*` are published first.... 

Something must be broken somewhere in that process.

I will have a closer look and let you know.

Stay tuned

**Comment by blackholegalaxy** [comment]
I also encounter the problem. Nx at 18.0.6. Angular and flutter project. We use `@nxrocks/nx-flutter` and bumping from 8.1.0 to 8.2.0 immediately created the error.

It impacts every NX command.

```
(0 , common_1.createNodesFor) is not a function


Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
If the error persists, please run "nx reset".
```

Downgrading to 8.1.0 fixes the issue.

Please note we use yarn `4.1.0`

**Comment by tinesoft** [comment]
Closing, as it should be fixed in latest version of the plugin
