### ISSUE TITLE
[Bug] `nx affected:lint` throws `Cannot find module 'hpagent'` after updating to v5.0.0 of the plugin

### ISSUE THREAD

**Issue by tschaffter** [tinesoft/nxrocks#128]
### Plugin Name

@nxrocks/nx-spring-boot

### Plugin Version

5.0.0

### Nx Version

14.5.4

### Expected Behaviour

The command `nx affected:lint` should work fine.

### Actual Behaviour

```console
$ nx affected:lint

 >  NX   Affected criteria defaulted to --base=main --head=HEAD

nx affected:lint

Run command using --base=[SHA1] (affected by the committed, uncommitted and untracked changes):
  --base  Base of the current branch (usually main)                                                                                                                                                                        [string]

or using --base=[SHA1] --head=[SHA2] (affected by the committed changes):
  --base  Base of the current branch (usually main)                                                                                                                                                                        [string]
  --head  Latest commit of the current branch (usually HEAD)                                                                                                                                                               [string]

or using:
  --files        Change the way Nx is calculating the affected command by providing directly changed files, list of files delimited by commas                                                                               [array]
  --uncommitted  Uncommitted changes                                                                                                                                                                                      [boolean]
  --untracked    Untracked changes                                                                                                                                                                                        [boolean]

Options:
  --help              Show help                                                                                                                                                                                           [boolean]
  --version           Show version number                                                                                                                                                                                 [boolean]
  --parallel          Max number of parallel processes [default is 3]                                                                                                                                                      [string]
  --output-style      Defines how Nx emits outputs tasks logs                                                                                          [string] [choices: "dynamic", "static", "stream", "stream-without-prefixes"]
  --all               All projects                                                                                                                                                                                        [boolean]
  --exclude           Exclude certain projects from being processed                                                                                                                                           [array] [default: []]
  --runner            This is the name of the tasks runner configured in nx.json                                                                                                                                           [string]
  --skip-nx-cache     Rerun the tasks even when the results are available in the cache                                                                                                                   [boolean] [default: false]
  --configuration     This is the configuration to use when performing tasks on projects                                                                                                                                   [string]
  --only-failed       Isolate projects which previously failed        [deprecated: The command to rerun failed projects will appear if projects fail. This now does nothing and will be removed in v15.] [boolean] [default: false]
  --verbose           Print additional error stack trace on failure                                                                                                                                                       [boolean]
  --nx-bail           Stop command execution after the first failed task                                                                                                                                 [boolean] [default: false]
  --nx-ignore-cycles  Ignore cycles in the task graph                                                                                                                                                    [boolean] [default: false]

Examples:
  affected --target=custom-target                         Run custom target for all affected projects
  affected --target=test --parallel=5                     Run tests in parallel
  affected --target=test --all                            Run the test target for all projects
  affected --target=test --files=libs/mylib/src/index.ts  Run tests for all the projects affected by changing the index.ts file
  affected --target=test --base=main --head=HEAD          Run tests for all the projects affected by the changes between main and HEAD (e.g., PR)
  affected --target=test --base=main~1 --head=main        Run tests for all the projects affected by the last commit on main

Find more information and examples at https://nx.dev/cli/affected

Error: Cannot find module 'hpagent'
Require stack:
- /workspaces/challenge-registry/node_modules/@nxrocks/common/src/lib/core/utils/utils.js
- /workspaces/challenge-registry/node_modules/@nxrocks/common/src/lib/core/utils/index.js
- /workspaces/challenge-registry/node_modules/@nxrocks/common/src/lib/core/jvm/utils.js
- /workspaces/challenge-registry/node_modules/@nxrocks/common/src/lib/core/jvm/index.js
- /workspaces/challenge-registry/node_modules/@nxrocks/common/src/index.js
- /workspaces/challenge-registry/node_modules/@nxrocks/nx-spring-boot/src/utils/boot-utils.js
- /workspaces/challenge-registry/node_modules/@nxrocks/nx-spring-boot/src/generators/project/lib/generate-boot-project.js
- /workspaces/challenge-registry/node_modules/@nxrocks/nx-spring-boot/src/generators/project/lib/index.js
- /workspaces/challenge-registry/node_modules/@nxrocks/nx-spring-boot/src/generators/project/generator.js
- /workspaces/challenge-registry/node_modules/@nxrocks/nx-spring-boot/src/index.js
- /workspaces/challenge-registry/node_modules/nx/src/utils/nx-plugin.js
- /workspaces/challenge-registry/node_modules/nx/src/config/workspaces.js
- /workspaces/challenge-registry/node_modules/nx/src/project-graph/file-utils.js
- /workspaces/challenge-registry/node_modules/nx/src/command-line/affected.js
- /workspaces/challenge-registry/node_modules/nx/src/command-line/nx-commands.js
- /workspaces/challenge-registry/node_modules/nx/bin/init-local.js
- /workspaces/challenge-registry/node_modules/nx/bin/nx.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (/workspaces/challenge-registry/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/workspaces/challenge-registry/node_modules/@nxrocks/common/src/lib/core/utils/utils.js:5:19)
    at Module._compile (/workspaces/challenge-registry/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/workspaces/challenge-registry/node_modules/@nxrocks/common/src/lib/core/utils/utils.js',
    '/workspaces/challenge-registry/node_modules/@nxrocks/common/src/lib/core/utils/index.js',
    '/workspaces/challenge-registry/node_modules/@nxrocks/common/src/lib/core/jvm/utils.js',
    '/workspaces/challenge-registry/node_modules/@nxrocks/common/src/lib/core/jvm/index.js',
    '/workspaces/challenge-registry/node_modules/@nxrocks/common/src/index.js',
    '/workspaces/challenge-registry/node_modules/@nxrocks/nx-spring-boot/src/utils/boot-utils.js',
    '/workspaces/challenge-registry/node_modules/@nxrocks/nx-spring-boot/src/generators/project/lib/generate-boot-project.js',
    '/workspaces/challenge-registry/node_modules/@nxrocks/nx-spring-boot/src/generators/project/lib/index.js',
    '/workspaces/challenge-registry/node_modules/@nxrocks/nx-spring-boot/src/generators/project/generator.js',
    '/workspaces/challenge-registry/node_modules/@nxrocks/nx-spring-boot/src/index.js',
    '/workspaces/challenge-registry/node_modules/nx/src/utils/nx-plugin.js',
    '/workspaces/challenge-registry/node_modules/nx/src/config/workspaces.js',
    '/workspaces/challenge-registry/node_modules/nx/src/project-graph/file-utils.js',
    '/workspaces/challenge-registry/node_modules/nx/src/command-line/affected.js',
    '/workspaces/challenge-registry/node_modules/nx/src/command-line/nx-commands.js',
    '/workspaces/challenge-registry/node_modules/nx/bin/init-local.js',
    '/workspaces/challenge-registry/node_modules/nx/bin/nx.js'
  ]
}
```

The plugin was installed in two ways, each of them leading to this issue:

- Upgrading the plugin: `yarn upgrade --latest @nxrocks/nx-spring-boot`
- Remove and add again the plugin

I noticed that the command `nx affected:lint` does not fail if I remove `@nxrocks/nx-spring-boot` from the array `plugins` in `nx.json`. After removal:

```console
$ nx affected:lint

 >  NX   Affected criteria defaulted to --base=main --head=HEAD


    ✔  nx run challenge-registry:lint  [existing outputs match the cache, left as is]
    ✔  nx run challenge-registry-challenge-search:lint  [existing outputs match the cache, left as is]
    ✔  nx run challenge-registry-e2e:lint  [existing outputs match the cache, left as is]
    ✔  nx run challenge-registry-user-profile:lint  [existing outputs match the cache, left as is]
    ✔  nx run challenge-registry-org-profile:lint  [existing outputs match the cache, left as is]
    ✔  nx run challenge-registry-org-search:lint  [existing outputs match the cache, left as is]
    ✔  nx run challenge-registry-challenge:lint  [existing outputs match the cache, left as is]
    ✔  nx run challenge-registry-not-found:lint  [existing outputs match the cache, left as is]
    ✔  nx run challenge-registry-config:lint  [existing outputs match the cache, left as is]
    ✔  nx run challenge-registry-signup:lint  [existing outputs match the cache, left as is]
    ✔  nx run challenge-registry-about:lint  [existing outputs match the cache, left as is]
    ✔  nx run challenge-registry-login:lint  [existing outputs match the cache, left as is]
    ✔  nx run challenge-registry-home:lint  [existing outputs match the cache, left as is]
    ✔  nx run challenge-registry-auth:lint  [existing outputs match the cache, left as is]
    ✔  nx run challenge-platform-e2e:lint  [existing outputs match the cache, left as is]
    ✔  nx run challenge-registry-ui:lint  [existing outputs match the cache, left as is]
    ✔  nx run shared-web-components:lint  [existing outputs match the cache, left as is]
    ✔  nx run challenge-platform:lint  [existing outputs match the cache, left as is]
    ✔  nx run api-angular:lint  [existing outputs match the cache, left as is]
    ✔  nx run shared-util:lint  [existing outputs match the cache, left as is]
    ✔  nx run api-spec:lint  [existing outputs match the cache, left as is]

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target lint for 21 projects (190ms)
```

### Steps to reproduce the behaviour

See above.

**Comment by tinesoft** [comment]
Thanks for reporting the issue @tschaffter.
It's weird that my smoke tests didn't catch that...
I will provide a fix asap...

**Comment by tinesoft** [comment]
Out of curiosity, 

- does running `nx build` command instead work? (this is what I do during the smoke tests)
- are you connected to a proxy server  or have env variable `http_proxy` or `https_proxy` (upper or lowercase) set ?

Thanks

**Comment by tschaffter** [comment]
Yes, the issue is also triggered when running `build` tasks:

```console
$ nx run-many --target=build
nx run-many

Run target for multiple listed projects

Options:
  --help              Show help                                                                    [boolean]
  --version           Show version number                                                          [boolean]
  --target            Task to run for affected projects                                  [string] [required]
  --parallel          Max number of parallel processes [default is 3]                               [string]
  --output-style      Defines how Nx emits outputs tasks logs
                                [string] [choices: "dynamic", "static", "stream", "stream-without-prefixes"]
  --projects          Projects to run (comma delimited)                                             [string]
  --all               [deprecated] Run the target on all projects in the workspace [boolean] [default: true]
  --runner            Override the tasks runner in `nx.json`                                        [string]
  --skip-nx-cache     Rerun the tasks even when the results are available in the cache
                                                                                  [boolean] [default: false]
  --configuration     This is the configuration to use when performing tasks on projects            [string]
  --only-failed       Only run the target on projects which previously failed
   [deprecated: The command to rerun failed projects will appear if projects fail. This now does nothing and
                                                         will be removed in v15.] [boolean] [default: false]
  --exclude           Exclude certain projects from being processed                    [array] [default: []]
  --verbose           Print additional error stack trace on failure                                [boolean]
  --nx-bail           Stop command execution after the first failed task          [boolean] [default: false]
  --nx-ignore-cycles  Ignore cycles in the task graph                             [boolean] [default: false]

Examples:
  run-many --target=test                                  Test all projects
  run-many --target=test --projects=proj1,proj2           Test proj1 and proj2
  run-many --target=test --projects=proj1,proj2           Test proj1 and proj2 in parallel
  --parallel=2

Find more information and examples at https://nx.dev/cli/run-many

Error: Cannot find module 'hpagent'
Require stack:
- /workspaces/challenge-registry/node_modules/@nxrocks/common/src/lib/core/utils/utils.js
- /workspaces/challenge-registry/node_modules/@nxrocks/common/src/lib/core/utils/index.js
- /workspaces/challenge-registry/node_modules/@nxrocks/common/src/lib/core/jvm/utils.js
- /workspaces/challenge-registry/node_modules/@nxrocks/common/src/lib/core/jvm/index.js
- /workspaces/challenge-registry/node_modules/@nxrocks/common/src/index.js
- /workspaces/challenge-registry/node_modules/@nxrocks/nx-spring-boot/src/utils/boot-utils.js
- /workspaces/challenge-registry/node_modules/@nxrocks/nx-spring-boot/src/generators/project/lib/generate-boot-project.js
- /workspaces/challenge-registry/node_modules/@nxrocks/nx-spring-boot/src/generators/project/lib/index.js
- /workspaces/challenge-registry/node_modules/@nxrocks/nx-spring-boot/src/generators/project/generator.js
- /workspaces/challenge-registry/node_modules/@nxrocks/nx-spring-boot/src/index.js
- /workspaces/challenge-registry/node_modules/nx/src/utils/nx-plugin.js
- /workspaces/challenge-registry/node_modules/nx/src/config/workspaces.js
- /workspaces/challenge-registry/node_modules/nx/src/project-graph/file-utils.js
- /workspaces/challenge-registry/node_modules/nx/src/project-graph/build-dependencies/typescript-import-locator.js
- /workspaces/challenge-registry/node_modules/nx/src/project-graph/build-dependencies/explicit-project-dependencies.js
- /workspaces/challenge-registry/node_modules/nx/src/project-graph/build-dependencies/index.js
- /workspaces/challenge-registry/node_modules/nx/src/project-graph/build-project-graph.js
- /workspaces/challenge-registry/node_modules/nx/src/project-graph/project-graph.js
- /workspaces/challenge-registry/node_modules/nx/src/utils/project-graph-utils.js
- /workspaces/challenge-registry/node_modules/nx/src/tasks-runner/utils.js
- /workspaces/challenge-registry/node_modules/nx/src/tasks-runner/run-command.js
- /workspaces/challenge-registry/node_modules/nx/src/command-line/run-many.js
- /workspaces/challenge-registry/node_modules/nx/src/command-line/nx-commands.js
- /workspaces/challenge-registry/node_modules/nx/bin/init-local.js
- /workspaces/challenge-registry/node_modules/nx/bin/nx.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (/workspaces/challenge-registry/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/workspaces/challenge-registry/node_modules/@nxrocks/common/src/lib/core/utils/utils.js:5:19)
    at Module._compile (/workspaces/challenge-registry/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/workspaces/challenge-registry/node_modules/@nxrocks/common/src/lib/core/utils/utils.js',
    '/workspaces/challenge-registry/node_modules/@nxrocks/common/src/lib/core/utils/index.js',
    '/workspaces/challenge-registry/node_modules/@nxrocks/common/src/lib/core/jvm/utils.js',
    '/workspaces/challenge-registry/node_modules/@nxrocks/common/src/lib/core/jvm/index.js',
    '/workspaces/challenge-registry/node_modules/@nxrocks/common/src/index.js',
    '/workspaces/challenge-registry/node_modules/@nxrocks/nx-spring-boot/src/utils/boot-utils.js',
    '/workspaces/challenge-registry/node_modules/@nxrocks/nx-spring-boot/src/generators/project/lib/generate-boot-project.js',
    '/workspaces/challenge-registry/node_modules/@nxrocks/nx-spring-boot/src/generators/project/lib/index.js',
    '/workspaces/challenge-registry/node_modules/@nxrocks/nx-spring-boot/src/generators/project/generator.js',
    '/workspaces/challenge-registry/node_modules/@nxrocks/nx-spring-boot/src/index.js',
    '/workspaces/challenge-registry/node_modules/nx/src/utils/nx-plugin.js',
    '/workspaces/challenge-registry/node_modules/nx/src/config/workspaces.js',
    '/workspaces/challenge-registry/node_modules/nx/src/project-graph/file-utils.js',
    '/workspaces/challenge-registry/node_modules/nx/src/project-graph/build-dependencies/typescript-import-locator.js',
    '/workspaces/challenge-registry/node_modules/nx/src/project-graph/build-dependencies/explicit-project-dependencies.js',
    '/workspaces/challenge-registry/node_modules/nx/src/project-graph/build-dependencies/index.js',
    '/workspaces/challenge-registry/node_modules/nx/src/project-graph/build-project-graph.js',
    '/workspaces/challenge-registry/node_modules/nx/src/project-graph/project-graph.js',
    '/workspaces/challenge-registry/node_modules/nx/src/utils/project-graph-utils.js',
    '/workspaces/challenge-registry/node_modules/nx/src/tasks-runner/utils.js',
    '/workspaces/challenge-registry/node_modules/nx/src/tasks-runner/run-command.js',
    '/workspaces/challenge-registry/node_modules/nx/src/command-line/run-many.js',
    '/workspaces/challenge-registry/node_modules/nx/src/command-line/nx-commands.js',
    '/workspaces/challenge-registry/node_modules/nx/bin/init-local.js',
    '/workspaces/challenge-registry/node_modules/nx/bin/nx.js'
  ]
}
```

I'm working in a VS Code dev container running on a remote host (AWS EC2).

```console
vscode@9099a05e6679:/workspaces/challenge-registry$ echo $http_proxy

vscode@9099a05e6679:/workspaces/challenge-registry$ echo $HTTP_PROXY

vscode@9099a05e6679:/workspaces/challenge-registry$ echo $https_proxy

vscode@9099a05e6679:/workspaces/challenge-registry$ echo $HTTPS_PROXY

```

**Comment by tinesoft** [comment]
Thanks for the confirmation Thomas.

I've found the issue (`hpagent` was declared as a `peerDependencies` instead of a `dependencies`).
The fix is quick easy. I just didn't understand why my dedicated [smoke test](https://github.com/tinesoft/nxrocks/blob/07eb0558546498c4ac8001e2d2fe0150cd689811/e2e/smoke/tests/smoke.test.ts#L137) didn't catch this...
But I've found my answer, the tests are base on NPM package manager, and contrary to Yarn (that you use), the  missing `hpagent`  was still installed by the first, even if it was declared as `peerDependencies`.
